---
- name: docker init
  hosts: localhost
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt:
        apt-transport-https
        ca-certificates
        curl
        software-properties-common
        python3-pip
        virtualenv
        python3-setuptools
      state: present
      update_cache: yes
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull default Docker image
      docker_image:
        name: docker_ubuntu
        source: pull
    - name: Create default containers
      docker_container:
        name: docker1
        image: ubuntu:18.04
        command: sleep 1d
